### ISSUE TITLE
Programming the cellular automata

### ISSUE THREAD

**Issue by yurimarca** [sigevo-summer-school-2018/Analyzing-tiger-mosquito-disease-spread#5]
Bi-dimensional cellula automata using the encoding of the rules from preview task.

**Comment by fcofdezdevega** [comment]
There are many places that you may found in google related to how to program the game of life (a bi-dimensional automata with a specific set of rules), such as:
  https://gamedevelopment.tutsplus.com/tutorials/creating-life-conways-game-of-life--gamedev-558

**Comment by fcofdezdevega** [comment]
Try to begin programming a well known two-dimensional cellular automata, such as the game of life, so that you understand how they work.  Try to encode the rules in the way you decide with your colleagues programming the GA.  This way, when they provide you new rules, it will be easy to change them and the CA will work with the new rules.
